-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnpWNjbTU96FBDsGN
QFKw/LufZyCbosNiIXQN0QkDqtigCgYIKoZIzj0DAQehRANCAATv7USd1DjnN41D
veqVrigL8UhEILNMnqXRnuM4PIupAfY7ZeFOSfMnCtvfNPmVGessxp8Kvzicl4Th
WKMOVDfd
-----END PRIVATE KEY-----